src/objects/Change_Management_Integration_Credential__c.object
<CustomObject>
    <description>This object stores the authentication credentials to the external system.</description>
    <fields>
        <fullName>Authentication_Method__c</fullName>
        <label>Authentication Method</label>
        <picklist>
            <picklistValues>
                <fullName>Basic Authentication</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Authentication Token</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Endpoint__c</fullName>
        <label>Endpoint</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>External_System__c</fullName>
        <label>External System</label>
        <picklist>
            <picklistValues>
                <fullName>JIRA</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>VersionOne</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rally</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agile Accelerator</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Change Management Integration</label>
    <nameField>
        <label>Integration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Change Management Integrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ChangeManagementIntegrationTriggerTest.cls
@isTest
private class ChangeManagementIntegrationTriggerTest {
	static testMethod void testEncoding(){
		Change_Management_Integration_Credential__c cred = new Change_Management_Integration_Credential__c();
		cred.Name = 'My Credential';
		cred.External_System__c = 'Jira';
		cred.Authentication_Method__c = 'Basic Authentication';
		cred.Username__c = 'MyUsername';
		cred.Password__c = 'MyPassword';
		cred.Endpoint__c = 'http://endpoint.com';

		Test.startTest();
		insert cred;
		Test.stopTest();
		List<Change_Management_Integration_Credential__c> results = [select Id, Name, Password__c from Change_Management_Integration_Credential__c];
		system.assertEquals(1, results.size(), 'Results query returned no results');
		system.assertEquals('TXlQYXNzd29yZA==', results.get(0).Password__c, 'The expected password encoded string did not match.');
	}
}